config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :listing_deals do
    resources :bids, only: [ :new, :create, :index, :edit, :update ]
  end

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :product
  belongs_to :listing_deal
  belongs_to :user

  validates :product, presence: true
  validates :listing_deal, presence: true
  validates :user, presence: true
  validates :amount, presence: true, numericality: { only_integer: true }
  # validate :amount_cannot_be_less_than_min_amount

  def amount_cannot_be_less_than_min_amount
    min_amount = ListingDeal.find(listing_deal_id).min_amount
    if !amount
      errors.add(:amount, "Please enter and amount")
    elsif amount <= min_amount
      errors.add(:amount, "You need to bid at least the minimum amount." )
    end
  end
end

app/models/listing_deal.rb
class ListingDeal < ApplicationRecord
  belongs_to :user
  has_many :bids, dependent: :destroy

  validates :user, presence: true
  validates :min_amount, presence: true
  validates :volume, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  # has_many :listing_deals, dependent: :destroy
  has_many :bids, dependent: :destroy

  validates :name, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_sign_up_parameters, if: :devise_controller?

  protected

  def configure_sign_up_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [
        :name,
        :address,
        :phone_number,
        :is_venue,
      ])
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :find_listing_deal, only: [ :new, :create, :update ]
  before_action :find_bid, only: [ :edit, :update ]

  def new
    @bid = Bid.new
  end

  def create
    @bid = Bid.new(bid_params)
    @bid.listing_deal = @listing_deal
    @bid.product = Product.find(@listing_deal.product_id)
    @bid.user = current_user
    if @bid.save
      redirect_to listing_deal_path(@listing_deal)
    else
      redirect_to listing_deal_path(@listing_deal), alert: "Unable to create listing"
    end
  end

  def edit
  end

  def update
    @bid.accepted = true
    @bid.save
    @listing_deal.completed_at = Date.today
    @listing_deal.save
    redirect_to listing_deal_path(@listing_deal)
  end

  private

  def bid_params
    params.require(:bid).permit(:amount, :description)
  end

  def find_listing_deal
    @listing_deal = ListingDeal.find(params[:listing_deal_id])
  end

  def find_bid
    @bid = Bid.find(params[:id])
  end
end

app/controllers/listing_deals_controller.rb
class ListingDealsController < ApplicationController
  before_action :find_listing_deal, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category]
      # raise
      @listing_deals = ListingDeal.where(category:  params[:category])
    else
      @listing_deals = ListingDeal.all
    end
  end

  def show
    @product = Product.find(@listing_deal.product_id)
    @bids = @listing_deal.bids
    @bid = Bid.new
    @accepted_bid = @bids.where(accepted: true).first
    @highest_bid = @bids.order("amount DESC").limit(1).first
  end

  def new
    @listing_deal = ListingDeal.new
  end

  def create
    @listing_deal = ListingDeal.new(listing_deal_params)
    @listing_deal.user = current_user
    @listing_deal.product_id = 1
    if @listing_deal.save
      redirect_to listing_deal_path(@listing_deal), alert: "Deal listed successfully"
    else
      raise
      render :new
    end
  end

  def update
    @listing_deal.update(listing_deal_params)
      if @listing_deal.save
        redirect_to listing_deal_path
      else
        render :new
      end
  end

  def destroy
    @listing_deal.destroy
    redirect_to listing_deals_path, alert: "Listing deleted"
  end

  private

  def find_listing_deal
    @listing_deal = ListingDeal.find(params[:id])
  end

  def listing_deal_params
    params.require(:listing_deal).permit(:product_id, :user_id, :min_amount, :other_requirements, :start_date, :end_date, :volume)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  def show
    if !@user.is_venue
      @bids = Bid.where(user_id: @user.id)
      @active_bids = Bid.joins(:listing_deal).where(user_id: @user.id).where(listing_deal: { completed_at: nil })
      @accepted_bids = Bid.where(user_id: @user.id, accepted: true)
    else
      @listing_deals = ListingDeal.where(user_id: @user.id)
      @accepted_listings = ListingDeal.where(user_id: @user.id).where.not(completed_at: nil)
      @active_listings = ListingDeal.where(user_id: @user.id, completed_at: [nil, ""])
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bids/_accept.html.erb
<%= simple_form_for [ listing_deal, bid ], method: :patch, url: listing_deal_bid_path(listing_deal, bid) do |f| %>
  <%= f.button :submit, "Accept this bid", class: 'btn btn-primary' %>
<% end %>

app/views/bids/_error_messages.html.erb
<% if @bid.errors.any? %>
  <ul>
    <% @bid.errors.full_messages.each do  |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/bids/_new.html.erb
<div class="form-inputs">
  <h4>Place your bid</h4>
  <%= simple_form_for [ @listing_deal, @bid ], method: :post, url: listing_deal_bids_path(@listing_deal) do |f| %>
    <%= f.error_notification %>
    <%= f.input :amount,
                hint: 'Must be higher than the minimum bid',
                required: true,
                label: false,
                placeholder: 'What\'s your offer?',
                class: 'form-inline' %>
    <%= f.input :description,
                label: false,
                placeholder: 'Any extras?',
                class: 'form-inline' %>
    <div class="form-actions">
      <%= f.button :submit, "Place bid", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eztenda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/listing_deals/_all_bids.html.erb
<!-- only displayed if the current user of the listing is the venue who created the tender -->
<div class="bid-container">
  <% bids.order(:amount).reverse.each do |bid| %>
    <div class="bid-card">
      <div class="bid-details col-8">
        <h5>Bid: £<%= bid.amount %></h5>
        <p>Offer: <%= bid.description %></p>
        <p>Brand: <%= bid.user.name %></p>
        <p>Product: <%= bid.product.name %></p>
      </div>
      <div class="accept-button col-4">
        <% if current_user == listing_deal.user %>
          <%= render './bids/accept', listing_deal: listing_deal, bid: bid %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/listing_deals/_auction_over.html.erb
<div class="accepted-bid-card">
  <p>This auction is over, and a bid has been accepted!</p>
  <div class="bid-card">
    <div class="bid-details col-8">
      <h5>Offer: £<%= accepted_bid.amount %></h5>
      <p>Brand: <%= accepted_bid.user.name %></p>
      <p>Product: <%= accepted_bid.product.name %></p>
    </div>
  </div>
</div>

app/views/listing_deals/_form.html.erb
 <%= simple_form_for listing_deal do |f| %>
  <%= f.input :category,
              placeholder: 'Category e.g. lager, white wine, soft drinks',
              collection: ['Beer', 'Cider', 'White Wine', 'Red Wine', 'Champagne', 'Soft Drinks', 'Spirits'],
              selected: 'Beer'
  %>
  <%= f.input :volume, label: 'Estimated volume of product to be sold' %>
  <%= f.input :min_amount, label: 'Minimum Bid' %>
  <%= f.input :other_requirements, label: 'Any other requirements? e.g. specific wholesaler, marketing or POS information' %>
  <%= f.input :start_date, as: :date, html5: true, label: 'Start date for listing period' %>
  <%= f.input :end_date, as: :date, html5: true, label: 'End date for listing period' %>
  <%= f.submit "Save Listing!", class: "btn btn-primary" %>
<% end %>

app/views/listing_deals/_product_icons.html.erb
<div class="product-icons">
 <% case @product.category %>
  <% when'Beer' %>
    <i class="fas fa-beer"></i>
  <% when 'Lager' %>
    <i class="fas fa-beer"></i>
  <% when 'Cider' %>
    <i class="fas fa-beer"></i>
  <% when 'White wine' %>
    <i class="far fa-wine-glass-alt"></i>
  <% when 'Red wine' %>
    <i class="fas fa-wine-glass-alt"></i>
  <% when 'Champagne' %>
    <i class="fal fa-glass-champagne"></i>
  <% when 'Soft drinks' %>
    <i class="fas fa-cocktail"></i>
  <% when 'Spirits' %>
    <i class="fas fa-cocktail"></i>
  <% end %>
<% end %>
</div>

app/views/listing_deals/_user_is_venue.html.erb
<!-- only displayed if the current user of the listing is the venue who created the tender -->
<div class="bid-container">
  <% bids.order(:amount).reverse.each do |bid| %>
    <div class="bid-card">
      <div class="bid-details col-8">
        <h5>Offer: £<%= bid.amount %></h5>
        <p>Brand: <%= bid.user.name %></p>
        <p>Product: <%= bid.product.name %></p>
      </div>
      <div class="accept-button col-4">
        <% if current_user == listing_deal.user %>
          <%= render './bids/accept', listing_deal: listing_deal, bid: bid %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/listing_deals/edit.html.erb
<div class="form-container">
  <%= render 'form', listing_deal: @listing_deal %>
</div>

app/views/listing_deals/index.html.erb
<div class="listing-container">
<div class="listing-index">
  <div class="filter-index">
      <%= render '/shared/filter' %>
  </div>
  <div class="listing-deals">
    <h1 class="listing-header">Live Listings</h1>
      <div class="row">
        <% @listing_deals.each do |listing_deal| %>
          <div class="col-4 col-sm-3">
          <div class="listing-card shadow">

            <div class="listing-details">
              <ul id="list">
                <li><h4><%= link_to listing_deal.user.name, listing_deal_path(listing_deal.id) %></h4></li>
                <li><strong>Category:</strong> <%= listing_deal.category %>
                  <% case listing_deal.category %>
                    <% when'Beer' %>
                      <i class="fas fa-beer"></i>
                    <% when 'Lager' %>
                      <i class="fas fa-beer"></i>
                    <% when 'Cider' %>
                      <i class="fas fa-beer"></i>
                    <% when 'White Wine' %>
                      <i class="fas fa-wine-glass-alt"></i>
                    <% when 'Red Wine' %>
                      <i class="fas fa-wine-glass-alt"></i>
                    <% when 'Champagne' %>
                      <i class="fas fa-glass-cheers"></i>
                    <% when 'Soft drinks' %>
                      <i class="fas fa-cocktail"></i>
                    <% when 'Spirits' %>
                      <i class="fas fa-cocktail"></i>
                  <% end %></li>
                <li><strong>Volume:</strong> <%= listing_deal.volume %></li>
                <li><strong>Start:</strong> <%= listing_deal.start_date.strftime("%a %e %b %y") %></li>
                <li><strong>End:</strong> <%= listing_deal.end_date.strftime("%a %e %b %y") %></li>
                <li><strong>Minimum Bid:</strong> £<%= listing_deal.min_amount %></li>
                <li><strong>Other:</strong> <%= listing_deal.other_requirements %></li>

              </ul>
            </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
     <div class="index-page-links">
      <% if current_user.is_venue %>
        <%= link_to 'New Listing', new_listing_deal_path, class: "btn btn-primary" %>
      <% end %>
    </div>

</div>

app/views/listing_deals/new.html.erb
<div class="form-container">
  <h3>Add your listing</h3>
  <%= render 'form', listing_deal: @listing_deal %>
</div>

app/views/listing_deals/show.html.erb
<div class="container show-page">
  <div class="row py-5">
    <div class="col-xs-12 show-card shadow">
      <div class="venue-header">
        <h1><%= @listing_deal.user.name %></h1>
      </div>
      <div class="show-card-content">
      <div class="tender-container">
      <h2>Tender Details</h2>
        <ul>
          <li>
            <h5>
              <%= @listing_deal.volume %> of <%= @listing_deal.category %>
              <% case @listing_deal.category %>
                <% when 'Lager' %>
                  <i class="fas fa-beer"></i>
                <% when 'Cider' %>
                  <i class="fas fa-beer"></i>
                <% when 'White Wine' %>
                  <i class="far fa-wine-glass-alt"></i>
                <% when 'Red Wine' %>
                  <i class="fas fa-wine-glass-alt"></i>
                <% when 'Champagne' %>
                  <i class="fas fa-glass-cheers"></i>
                <% when 'Soft drinks' %>
                  <i class="fas fa-cocktail"></i>
                <% when 'Spirits' %>
                  <i class="fas fa-cocktail"></i>
              <% end %>
            </h5>
          </li>
          <li>From <strong> <%= @listing_deal.start_date.strftime("%a %e %b %y") %></strong> to <strong><%= @listing_deal.end_date.strftime("%a %e %b %y") %></strong></li>
          <li>Minimum Bid: <strong>£<%= @listing_deal.min_amount %></strong></li>
          <li>Other Requirements: <%= @listing_deal.other_requirements.nil? ? "None" : @listing_deal.other_requirements %></li>
        </ul>
      </div>
      <div class="listing-deals-bids mb-3">
        <h3>Auction</h3>
        <% if @listing_deal.bids.pluck('accepted').include?(true) %> <!--- auction is over --->
          <%= render "auction_over", accepted_bid: @accepted_bid %>
        <% else %> <!---- auction is still going ---->
          <div class="bid-top-stats">
            <div class="bid-count mr-5">
              Total Bids: <strong><%= @bids.count %></strong>
            </div>
            <% if !@highest_bid.nil? %>
              <div class="highest-bid mr-3">
                Highest Bid:  <strong class="highest-bid-value">£<%= @highest_bid.amount %></strong>
              </div>
              <div class="highest-bidder">
                (<strong><%= @highest_bid.user.name %></strong> bid on <%= @highest_bid.created_at.strftime("%a %e %b %y") %>)
              </div>
            <% end %>
          </div>
          <div>
              <% if current_user.is_venue == false %>
                <%= render "./bids/new" %>
              <% end %>
              <% if @listing_deal.user == current_user %>
                <%= render "all_bids", bids: @bids, listing_deal: @listing_deal %> <!--- if the current user is the venue for this listing --->
              <% end %>
          <% end %>
          </div>
          <div class="listing-deal-show-actions">
            <% if current_user.id == @listing_deal.user.id %>
              <%= link_to 'Edit this listing', edit_listing_deal_path(@listing_deal.id) %>
              <%= link_to 'Delete this listing', listing_deal_path(@listing_deal.id), method: :delete, data: { confirm: 'Are you sure?'} %>
            <% end %>
            <%= link_to 'Back to all listings', listing_deals_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner-info">
  <%= render '/shared/filter' %>
  <div class="container">

    <div class="row py-5">
      <div class="col-xs-12 col-sm-6 banner">
        <h1 class=" banner-heading">A great deal better</h1>
        <p class="mt-4 banner-text">The online auction where bars can tender their listings deals and brands can bid for them.</p>
        <div class="mt-5">
          <%= link_to listing_deals_path do %>
            <a href="#about"><button class="btn btn-dark">How it Works</button></a>
          <% end %>

        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= image_tag "bartender.png", class: "banner-image" %>
      </div>
    </div>
  </div>
</div>

<div class="container tenders">
  <div class="mt-5">
    <h1 class="text-center tender-text">Latest Tenders</h1>
    <div class="row">
      <% @listing_top = ListingDeal.last(3) %>


      <% @listing_top.each do |listing| %>
        <div class="col-4 mt-4">
          <div class="card shadow">
            <div class="card-body ml-2">
              <div class="card-text">

                <h2><%= link_to listing.user.name, listing_deal_path(listing.id) %></h2>
                <!-- we will need to change this to latest bid! -->
                <p> Current bid: <%= listing.min_amount %></p>
                <!-- need link -->
                <%= link_to 'Join Auction', listing_deal_path(listing.id), class: 'btn btn-primary' %>

              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
  <div class="marketing-info">
      <div class="container marketing">
    <div class="row py-5">
      <div class="col-xs-12 col-sm-6">
          <h1 class="marketing-heading" id="about">A better way for bars and brands to do business</h1>
      <div class="mt-4 marketing-text">

        <p>Listing deals between bars and drinks brands are essential.</p>
        <p>Eztenda is an online autction where bars can openly tender their listings deals and drinks brands can bid for them.</p>
        <p>Unlocks revenue for bar managers</p>
        <p>Secures distribution for drinks brands</p>
         <p>Easy and intuitive, welcome to Eztenda!</p>
      </div>
      <div class="marketing-link">
        <%= link_to listing_deals_path do %>
          <button class="btn btn-dark">View listings</button>
        <% end %>
      </div>

      </div>
  </div>


    </div>

  </div>

app/views/shared/_filter.html.erb
<div class="filter-bar">
  <div class="filter-links">
    <div class=""><%= link_to 'Lager', listing_deals_path(category: "Lager") %></div>
    <div class=""><%= link_to 'Cider', listing_deals_path(category: "Cider") %></div>
    <div class=""><%= link_to 'Red Wine', listing_deals_path(category: "Red Wine") %></div>
    <div class=""><%= link_to 'White Wine', listing_deals_path(category: "White Wine") %></div>
    <div class=""><%= link_to 'Champagne', listing_deals_path(category: "Champagne") %></div>
    <div class=""><%= link_to 'Soft Drinks', listing_deals_path(category: "Soft Drinks") %></div>
    <div class=""><%= link_to 'Spirits', listing_deals_path(category: "Spirit") %></div>
    <div class=""><%= link_to 'All Categories', listing_deals_path %></div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to "/", class: "navbar-brand my-2" do %>
      <%= image_tag "eztenda-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto align-items-center">
        <% if user_signed_in? %>

          <li class="mr-4">
            <% if !current_user.is_venue? %>
              <%= link_to "Explore listings", listing_deals_path, class: 'btn btn-primary' %>
            <% else %>
              <%= link_to "Create a Listing", new_listing_deal_path, class: "btn btn-primary" %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.abstractapi.com/v1?api_key=#{ENV['ABSTRACT_API_KEY']}&name=#{current_user.name}",
                class: "avatar dropdown-toggle",
                id: "navbarDropdown",
                data: { toggle: "dropdown" },
                'aria-haspopup': true,
                'aria-expanded': false
            %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "All listings", listing_deals_path, class: "dropdown-item" %>
              <% if current_user.is_venue == true %>
                <%= link_to 'Your Listings', current_user, class: "dropdown-item" %>
              <% else %>
                <%= link_to 'Your Bids', current_user, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_user_is_brand.html.erb
<h2 class="mb-3">Bids on active tenders</h2>
<div class="active-tenders mb-3">
  <% if @active_bids.nil? %>
    <p>You do not have any active bids! View the active listings below to join an auction.</p>
    <%= link_to "View listings", listing_deals_path, class: "btn btn-primary" %>
  <% else %>
    <% @active_bids.each do |bid| %>
      <% @product = Product.find(bid.listing_deal.product_id) %>
      <div class="col-4 mb-4">
        <div class="card shadow">
          <div class="card-body">
            <p class="card-text">Offer: £<%= bid.amount %></p>
            <p class="card-text">From: <%= bid.listing_deal.start_date.strftime("%a %e %b %y") %> to <%= bid.listing_deal.end_date.strftime("%a %e %b %y") %></p>
            <%= link_to listing_deal_path(bid.listing_deal) do %>
              <button class="btn btn-primary">See More</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<h2 class="mb-3">Agreed deals</h2>
<div class="agreed-deals mb-3">
  <% if @accepted_bids.nil? || @accepted_bids.empty? %>
    <p>You do not have any agreed deals.</p>
  <% else %>
    <% @accepted_bids.each do |bid| %>
        <% @product = Product.find(bid.listing_deal.product_id) %>
        <div class="col-4 mb-4">
          <div class="card shadow">
            <div class="card-body">
              <p class="card-text">Volume: <%= bid.listing_deal.volume %> of <%= @product.category %></p>
              <p class="card-text">From: <%= bid.listing_deal.start_date.strftime("%a %e %b %y") %> to <%= bid.listing_deal.end_date.strftime("%a %e %b %y") %></p>
              <%= link_to listing_deal_path(bid.listing_deal) do %>
                <button class="btn btn-primary">See More</button>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/users/_user_is_venue.html.erb
<h2 class="mb-3">Active tenders</h2>
<div class="active-tenders mb-3">
  <% if @active_listings.empty? %>
    <p>You do not have any active tenders!</p>
    <%= link_to "Create Listing", new_listing_deal_path, target: "_blank", class: "btn btn-primary" %>
  <% else %>
    <% @active_listings.each do |listing| %>
      <% @product = Product.find(listing.product_id) %>
      <div class="col-4 mb-4">
        <div class="card shadow">
          <div class="card-body">
            <p class="card-text">Volume: <%= listing.volume %> of <%= @product.category %></p>
            <p class="card-text">From: <%= listing.start_date.strftime("%a %e %b %y") %> to <%= listing.end_date.strftime("%a %e %b %y") %></p>
            <%= link_to listing_deal_path(listing) do %>
              <button class="btn btn-primary">See More</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<h2 class="mb-3">Agreed deals</h2>
<div class="agreed-deals mb-3">
  <% @accepted_listings.each do |listing| %>
    <% @product = Product.find(listing.product_id) %>
      <div class="col-4 mb-4">
        <div class="card shadow">
          <div class="card-body">
            <p class="card-text">Product: <%= @product.name %></p>
            <p class="card-text">Agreed on <%= listing.completed_at.strftime("%a %e %b %y") %></p>
            <p class="card-text">From: <%= listing.start_date.strftime("%a %e %b %y") %> to <%= listing.end_date.strftime("%a %e %b %y") %></p>
            <%= link_to listing_deal_path(listing) do %>
              <button class="btn btn-primary">See More</button>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row user-header">
    <h1 class="my-5 ">Welcome back, <%= @user.name %></h1>
  </div>
  <% if !current_user.is_venue %>
    <%= render "user_is_brand" %>
  <% else %>
    <%= render "user_is_venue" %>
  <% end %>
</div>